baseURL: "https://mnguyen0226.github.io/personal_site_v2/"
title: Minh T. Nguyen
theme: PaperMod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableMXL: true

languages:
    en:
        languageName: "English"
        weight: 1               # importance of the current page
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Posts
                  url: /
                  weight: 1
                - name: About
                  url: about/
                  weight: 2
                - name: Archive
                  url: archives
                  weight: 3
                - name: Search
                  url: search/
                  weight: 5
                - name: Categories
                  url: categories/
                  weight: 8
                - name: Tags
                  url: tags/
                  weight: 8

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Minh's Blog - https://github.com/adityatelange/hugo-PaperMod"
    author: Minh T. Nguyen

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: true
    images: ["papermod-cover.png"]

    homeInfoParams:
        Title: "👋 Hello, there (Xin Chào)"
        Content: >
            - ☕ Hi, this is Minh. I'm documenting my career and learning notes in this blog. 
            
            - 👀 **[I am currently looking for software engineer / machine learning / data science internship opportunities in summer 2023 and/or fall 2023.](https://www.linkedin.com/in/minhbtnguyen/)**

            - 🤝 Let's connect and discuss how I can provide service to your team! 

            - 📨 I am best reached via **mnguyen0226@vt.edu** or via direct message on **[LinkedIn](https://www.linkedin.com/in/minhbtnguyen/)**.

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/minhbtnguyen/"
        - name: github
          url: "https://github.com/mnguyen0226"
        - name: kaggle
          url: "https://www.kaggle.com/minhbtnguyen"
        - name: email
          url: "mnguyen0226@vt.edu"


    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: false
        favicon: "favicon/android-chrome-192x192.png"
        favicon16x16: "favicon/android-chrome-192x192.png"
        favicon32x32: "favicon/android-chrome-192x192.png"
        apple_touch_icon: "favicon/android-chrome-192x192.png"
        safari_pinned_tab: "favicon/android-chrome-192x192.png"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
